### ISSUE TITLE
Encoding not properly detected

### ISSUE THREAD

**Issue by simon-schlepphorst** [martin-ueding/songchecker#2]
The program crashes while reading this [file](https://github.com/martin-ueding/songchecker/files/449400/Shakira.-.Waka.Waka.This.Time.for.Africa.txt):

```
Traceback (most recent call last):
  File ".local/bin/songchecker", line 9, in <module>
    load_entry_point('songchecker==0.1', 'console_scripts', 'songchecker')()
  File ".local/lib/python3.4/site-packages/songchecker-0.1-py3.4.egg/songchecker/__main__.py", line 53, in main
  File ".local/lib/python3.4/site-packages/songchecker-0.1-py3.4.egg/songchecker/parser.py", line 66, in main
  File ".local/lib/python3.4/site-packages/songchecker-0.1-py3.4.egg/songchecker/parser.py", line 26, in meta_file_to_dict
UnicodeDecodeError: 'cp949' codec can't decode byte 0xc1 in position 1889: illegal multibyte sequence
```

According to vim the file should be in `latin1` encoding.

**Comment by martin-ueding** [comment]
It seems that the detected encoding is `cp949` by the `chardet`. Perhaps `chardet` does not do as good as a job as Vim does?

One way would be to catch the `UnicodeDecodeError` and then reload the file with `latin1` as a last resort.

So the code would be something like this:

``` python
def properly_detect_encoding(filename):
    with open(filename, 'rb') as f:
        bytes_ = f.read()
        detected = chardet.detect(bytes_)

        # Try to open the file with the given encoding. Apparently `chardet`
        # detects `cp949` when it should be `latin1`. Therefore try the result
        # from `chardet.detect`. If that does not work, open it again with
        # `latin1`. If that works, it is `latin1`. If not, there cannot be done
        # anything more.
        try:
            with open(filename, encoding=detected['encoding']) as f:
                pass
        except UnicodeDecodeError:
            try:
                with open(filename, encoding='latin1') as f:
                    pass
            except UnicodeDecodeError:
                print('No idea what encoding is in {}. Giving up.'.format(filename))
                raise
            else:
                return 'latin1'
        else:
            return detected
```

I have not tested the code, so it might have some typo in it. Basically it tries to open the file with the encoding given from `chardet.detect`. If that does not work but `latin1` works, that is used instead.
